name: SSH Certificate Check

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - master

jobs:
  check-cert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
      - name: Check SSH Certificate
        id: check_cert
        run: |
          HOST=blabnl.netlify.app
          PORT=443
        
          STATUS=$(timeout 10 bash -c "echo > /dev/tcp/$HOST/$PORT && echo 'valid' || echo 'invalid'")

          if ["$STATUS" == "valid"]; then
            echo "SSH_CERT_STATUS=valid" >> $GITHUB_ENV
          else
            echo "SSH_CERT_STATUS=invalid" >> $GITHUB_ENV
          fi

      - name: Create new branch
        run: |
          git checkout -b update-badge

      - name: Create SSH Certificate Badge
        run: |
          if [ "${SSH_CERT_STATUS}" == "valid" ]; then
            COLOR=brightgreen
          else
            COLOR=red
          fi
          curl -o ssh-cert-status.svg "https://img.shields.io/badge/SSH%20Certificate-$STATUS-$COLOR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push badge
        run: |
          git add ssh-cert-status.svg
          git commit -m "Update SSH Certificate Status Badge"
          git push origin update-badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-badge
          title: "Update SSH Certificate Status Badge"
          body: "This PR updates the SSH certificate status badge."
