name: SSH Certificate Check

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  check-cert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check SSH Certificate
        id: check_cert
        run: |
          HOST=blabnl.netlify.app
          PORT=22
          if timeout 5 bash -c "</dev/ttcp/$HOST/$PORT"; then
            echo "SSH_CERT_STATUS=valid" >> $GITHUB_ENV
          else
            echo "SSH_CERT_STATUS=invalid" >> $GITHUB_ENV
          fi

      - name: Create SSH Certificate Badge
        run: |
          STATUS=${{ env.SSH_CERT_STATUS }}
          if [ "$STATUS" == "valid" ]; then
            COLOR=brightgreen
          else
            COLOR=red
          fi
          curl -o ssh-cert-status.svg "https://img.shields.io/badge/SSH%20Certificate-$STATUS-$COLOR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push badge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ssh-cert-status.svg
          git commit -m "Update SSH Certificate Status Badge"
          git push